/* Generated by Cython 0.29.30 */

#ifndef __PYX_HAVE__raypier__core__ctracer
#define __PYX_HAVE__raypier__core__ctracer

#include "Python.h"

#ifndef __PYX_HAVE_API__raypier__core__ctracer

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C unsigned int REFL_RAY;
__PYX_EXTERN_C unsigned int GAUSSLET;
__PYX_EXTERN_C unsigned int PARABASAL;

#endif /* !__PYX_HAVE_API__raypier__core__ctracer */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initctracer(void);
#else
PyMODINIT_FUNC PyInit_ctracer(void);
#endif

#endif /* !__PYX_HAVE__raypier__core__ctracer */
